version: '3.7'

# computers
services: 
  # 컴퓨터 1
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./index.js:/myfolder/index.js
      - ./email.js:/myfolder/email.js
     # - ./src:/myfolder/src
    ports:
      - 4000:4000
  # 컴퓨터 2
  my-database:
    image: mongo:5
    ports:
      - 27017:27017 # name resolution 시 port는 필요없음