version: '3.7'

# computers
services:
  # 컴퓨터 1
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/myfolder/src
    ports:
      - 3000:3000
    env_file:
      - ./.env.docker

  # 컴퓨터 2
  my-database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'mydocker'
      MYSQL_ROOT_PASSWORD: 'aksclsl31'
    ports:
      - 3306:3306
